# Generated by Django 4.1.7 on 2023-04-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.SmallIntegerField(default=0)),
                ('descrtiption', models.CharField(max_length=250)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('loaned_amount', models.SmallIntegerField(default=0)),
                ('genre', models.CharField(blank=True, max_length=30, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('thumbnail_path', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
