# Generated by Django 4.1.7 on 2023-04-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_event_user_author_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
