# Generated by Django 4.1.7 on 2023-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_remove_product_descrtiption_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.CharField(default='2023/04/15 09:09:35', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description not available', max_length=500),
        ),
    ]
