# Generated by Django 4.1.7 on 2023-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_delete_user_remove_author_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.CharField(default='2023/04/15 11:22:37', editable=False, max_length=30),
        ),
    ]
