# Generated by Django 4.1.7 on 2023-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_alter_event_last_update'),
        ('borrow', '0007_rename_release_date_product_date_added_and_more'),
    ]

    operations = [
    ]
