# Generated by Django 4.1.7 on 2023-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0009_alter_event_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Book', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.CharField(default='2023/04/16 08:20:21', editable=False, max_length=30),
        ),
    ]
