# Generated by Django 4.1.7 on 2023-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0013_alter_event_last_update_alter_event_loaned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='loaned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
