# Generated by Django 4.1.7 on 2023-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0014_alter_event_loaned_date_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='loaned_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
