# Generated by Django 4.1.7 on 2023-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0015_alter_event_last_update_alter_event_loaned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_path',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='defaults/placeholder-1.jpg', upload_to='images/'),
        ),
    ]
