# Generated by Django 4.1.7 on 2023-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0016_remove_product_thumbnail_path_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
