# Generated by Django 4.1.7 on 2023-04-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0017_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
