# Generated by Django 4.1.7 on 2023-04-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0019_alter_product_image_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='event',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.AddField(
            model_name='event',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='borrow.product'),
        ),
        migrations.AddField(
            model_name='event',
            name='return_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='borrow.userprofile'),
        ),
    ]
