# Generated by Django 4.1.7 on 2023-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0021_alter_event_return_date_alter_event_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-last_update']},
        ),
        migrations.AddField(
            model_name='event',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='loaned_amount',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
